### ISSUE TITLE
If "wait for Images" is active Elementor can't edit the pages

### ISSUE THREAD

**Issue by Nemesis77swe** [nkb-bd/matrix-pre-loader#8]
It seems like when "wait for Images" is activated, the Elementor can't edit the posts, it get stuck on the loader.

I guess it's waiting for something that's not loaded in the editor..

**Comment by nkb-bd** [comment]
I have pushed a new version in git, can you check it.
Thanks

**Comment by Nemesis77swe** [comment]
Hi again!

I can see that you have been working on the plug-in, text offset, animate in/ out (have no idea what it is)..
But, unfortunately when I'm trying to edit a page with Elementor...
.. It doesn't work, looks like it's still waiting for something, and the elementor never opens the page, it only displays the loader spinning..

May 22, 2020 01:36:40 Lukman Nakib <notifications@github.com>:

**Comment by nkb-bd** [comment]
I have fixed it , please check again

**Comment by nkb-bd** [comment]
from github repository

**Comment by Nemesis77swe** [comment]
I will take a look, what's the anim for?

-- 
Mkkhcnll May 24, 2020 20:49:47 Lukman Nakib <notifications@github.com>:

**Comment by Nemesis77swe** [comment]
Yes, the new update doesn't interfere with Elementor during loading..

-- 
Mkkhcnll May 24, 2020 20:50:43 Lukman Nakib <notifications@github.com>:

**Comment by nkb-bd** [comment]
Thanks for letting me know, I will change the animation css to animate.css next time
